In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'a': range(0,100), 'b':range(0,100)})
np.square(df)

       a     b
0      0     0
1      1     1
2      4     4
3      9     9
4     16    16
..   ...   ...
95  9025  9025
96  9216  9216
97  9409  9409
98  9604  9604
99  9801  9801

[100 rows x 2 columns]

In [ ]:



#Deprecated Code






df = df.sub(df.mean(axis=1),axis=0)
df_shifted = df.copy()


df_shifted.loc[-1] = [0,0,0,0]
df_shifted.index = df_shifted.index + 1 
df_shifted.sort_index(inplace=True)


df_squared = df.copy()
df_squared = df_squared.pow(2,axis=0)

df_squared = df_squared.sum(axis=1)
df_squared_shifted = df_squared.copy()

df_squared_shifted.loc[-1] = 0
df_squared_shifted.index = df_squared_shifted.index + 1
df_squared_shifted.sort_index(inplace=True)
df_squared = df_squared.mul(df_squared_shifted, axis=0, fill_value=0)

df_squared
## Take square root of the denominator
df_squared = df_squared.pow(0.5,axis=0)
df_squared

df = df.mul(df_shifted,axis=0)
df = df.sum(axis=1)
df
pr = df.div(df_squared, axis=0)
pr